import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer, Header } from '@/components/ui';
import Link from 'next/link';

import whatsAppIcon from '@/assets/icons/WhatsApp.png'
import Image from 'next/image';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "KSQ Pergamino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className='relative'>
      <body
        className={`${montserrat.className} antialiased relative`}
      >
        <Header />
        <Link href={'#'} className='fixed bottom-4 right-4 z-50'><Image alt='Icono de WhatsApp' src={whatsAppIcon} height={56} width={56} /></Link>
        {children}
        <Footer />
      </body>
    </html>
  );
}
