import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../globals.css";
import { auth } from '@/config/auth.config';
import { redirect } from 'next/navigation';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "KSQ Pergamino",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  if (session?.user) {
    redirect("/dashboard");
  }

  return (
    <html lang="es" className='relative'>
      <body
        className={`${montserrat.className} antialiased relative`}
      >
        {children}
      </body>
    </html>
  );
}
