import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Header } from './_components/header/header';

const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KSQ Pergamino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserratSans.variable}  antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
